### ISSUE TITLE
Partial boot z9X

### ISSUE THREAD

**Issue by MEH661905** [jjm2473/jjm2473.github.io#30]
Hi, I found your guide a helpful start with a z9x I can't get to boot. Can't flash either, but I'm stuck at step 2.  I can read the UART but can't get to enter commands. I get the start of the initialisation, but then stops after this: 
process_dte_fw_certificate: 0x0
get_dte_bootcode_rtk = 0x00000000
copy_img_from_emmc(00000000, 00000d00, 00180000, 00030000)
process_dte_bootcode_rtk: 0x0
jump to BL31: 0x80001000

There is no response to me holding/pressing ESC. I've forced Echo on to make sure I'm sending Ctrl[
Not sure where to go next?  Any ideas?  I'm reasonably technical (science background) but definitely not a programmer/developer.

**Comment by jjm2473** [comment]
Maybe bootloader broken. I don't know how to repare bootloader on RTD1619. I have only RTD1296 bootloader.

**Comment by MEH661905** [comment]
Thanks, I'll give it a try at the weekend.
